# Generated by Django 5.2.1 on 2025-05-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('salary_range', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('required_skills', models.JSONField(default=list)),
            ],
        ),
    ]
