# Generated by Django 5.2.1 on 2025-05-24 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='posting_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='required_skills',
            field=models.TextField(default=list),
        ),
    ]
