# Generated by Django 5.2.1 on 2025-05-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobposting_create_date_jobposting_updated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='create_date',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
