# Generated by Django 5.2.1 on 2025-05-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_create_date_jobposting_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
